# Install as /etc/systemd/system/aidot-mini.service.d/robot-client.conf
[Unit]
Wants=aidot-ros-bridge.service
After=aidot-ros-bridge.service

[Service]
ExecStart=
ExecStart=/opt/aidot-mini/bin/aidot-mini --robot
